site_name: DebiasedMT
docs_dir: docs
repo_url: https://github.com/wjm41/frag-pcore-screen

nav: 
  - Home: 'index.md'
  - 'User Guide': 'user_guide.md'
  - License: license.md
theme: 
  name: material
  features:
    - navigation.tabs

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js