#!/bin/bash
#SBATCH -J cleanup
#SBATCH -A LEE-WJM41-SL2-CPU
#SBATCH --nodes=1
#SBATCH --ntasks=12
#SBATCH --cpus-per-task=1
#SBATCH --time=00:20:00
#SBATCH --mail-user=wjm41@cam.ac.uk
#SBATCH --mail-type=END,FAIL
#SBATCH -p cclake

. /etc/profile.d/modules.sh
module purge
#module load rhel7/default-peta4
module load rhel7/default-ccl
module load miniconda/3
source activate felix_md

while read fname; do
for n in {0..11}; do
fold_name=$(cat $fname)
echo "Doing $n-th cleanup for $fname, $fold_name"
mpirun -np 12 -ppn 12 python mpi_cleanup.py $1 $n
#mpirun -np 12 -ppn 12 python mpi_smiles.py $1 $n

#cat $fold_name/mols_cleanup_${n}_mpi_* > $fold_name/mols${n}_new.smi
#mv $fold_name/mols${n}_new.smi $fold_name/mols${n}.smi

python cleanup.py $1 $n 12
rm $fold_name/mols_cleanup_${n}_mpi_* 
done 
done<$1
