#!/bin/bash
#SBATCH -J gen_topN_$target
#SBATCH -A LEE-SL3-CPU
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --array=0-55
#SBATCH --time=12:00:00
#SBATCH --mail-user=wjm41@cam.ac.uk
#SBATCH --mail-type=END,FAIL
#SBATCH -p cclake

. /etc/profile.d/modules.sh
module purge
module load rhel7/default-ccl
module load miniconda/3
source activate felix_md

data_dir=/rds-d2/user/wjm41/rds-enaminereal-ZNFRY9wKoeE/EnamineREAL/folds/all_folds
if [ $SLURM_ARRAY_TASK_ID -lt 10 ]; then
echo fold0$SLURM_ARRAY_TASK_ID
folder=fold0$SLURM_ARRAY_TASK_ID
else 
echo fold$SLURM_ARRAY_TASK_ID
folder=fold$SLURM_ARRAY_TASK_ID
fi

script_dir=/rds-d2/user/wjm41/rds-enaminereal-ZNFRY9wKoeE/EnamineREAL/scripts

python $script_dir/gen_topN.py -N 50000 -fname $data_dir/$folder -target $target
