#!/bin/bash
#SBATCH -J mpi_butina_selection
#SBATCH --time=0:30:00
#SBATCH -A LEE-WJM41-SL2-CPU
#SBATCH --nodes=1
#SBATCH --ntasks=19
#SBATCH --cpus-per-task=4
#SBATCH --mail-type=ALL
#SBATCH --mail-user=wjm41@cam.ac.uk
##SBATCH --no-requeue
#SBATCH -p icelake-himem
#SBATCH --output=/home/wjm41/ml_physics/frag-pcore-screen/slurm_logs/subm_selection.out

. /etc/profile.d/modules.sh
module purge
module load rhel8/default-icl
module load miniconda/3
source activate fresco

# python butina_selection.py -target $1 --useFeatures
script_dir=/home/wjm41/ml_physics/frag-pcore-screen/scripts
# mpirun -np 19 -ppn 19 python butina_selection_mpi.py -target $1 --useFeatures

mpirun -np 19 -ppn 19 python $script_dir/butina_selection_mpi.py -target $1 --useFeatures --topN 10000 --suffix test_10k
