#!/bin/bash
#SBATCH -J taut_filter_mac1
#SBATCH --time=0:30:00
#SBATCH -A LEE-WJM41-SL2-CPU
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=76
#SBATCH --mail-type=ALL
#SBATCH --mail-user=wjm41@cam.ac.uk
##SBATCH --no-requeue
#SBATCH -p icelake

. /etc/profile.d/modules.sh
module purge
module load rhel8/default-icl
module load miniconda/3
source activate fresco

mpirun -np 76 -ppn 76 python filter.py
