#!/bin/bash
#SBATCH -J big_fold
#SBATCH -A LEE-SL3-CPU
#SBATCH --nodes=1
#SBATCH --ntasks=12
#SBATCH --cpus-per-task=1
#SBATCH --time=12:00:00
#SBATCH --mail-user=wjm41@cam.ac.uk
#SBATCH --mail-type=END,FAIL
#SBATCH -p cclake

. /etc/profile.d/modules.sh
module purge
module load rhel7/default-peta4
module load miniconda/3
source activate felix_md

echo $1
while read fname; do
for n in {0..11}; do
echo "Doing $n-th processing for $fname"
mpirun -np 12 -ppn 12 python mpi_cleanup.py $1 $n
#mpirun -np 12 -ppn 12 python mpi_smiles.py $1 $n

python cleanup.py $1 $n 12
cat $fname/mols_cleanup_${n}_mpi_* > $fname/mols${n}_new.smi
mv $fname/mols${n}_new.smi $fname/mols${n}.smi
rm $fname/mols_cleanup_${n}_mpi_*
done
done<$1
