#!/bin/bash
#SBATCH -J extract_real
#SBATCH -A LEE-SL3-CPU
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=12:00:00
#SBATCH --mail-user=wjm41@cam.ac.uk
#SBATCH --mail-type=END,FAIL
#SBATCH -p cclake

. /etc/profile.d/modules.sh
module purge
module load rhel7/default-peta4
module load miniconda/3
source activate felix_md
module load gcc/5
module load openbabel/2.4.0

./extract.sh $1
